version: '3'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: gistapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql

  pi-app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      POSTGRES_DB: gistapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
